services:
  ssr:
    build: .
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heddle-main.rule=Host(`heddle.fhub.dev`)"
      - "traefik.http.routers.heddle-main.entrypoints=https"
      - "traefik.http.routers.heddle-main.tls=true"
      - "traefik.http.routers.heddle-main.tls.certresolver=le"
      - "traefik.http.services.heddle-main.loadbalancer.server.port=5173"
    environment:
      - NODE_ENV=production

  playground:
    build:
      context: ./playground
      dockerfile: Dockerfile
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heddle-playground.rule=Host(`heddle.fhub.dev`) && PathPrefix(`/playground`)"
      - "traefik.http.routers.heddle-playground.entrypoints=https"
      - "traefik.http.routers.heddle-playground.tls=true"
      - "traefik.http.routers.heddle-playground.tls.certresolver=le"
      - "traefik.http.services.heddle-playground.loadbalancer.server.port=80"
    environment:
      - NODE_ENV=production

networks:
  traefik_proxy:
    external: true
