services:
  ssr:
    build: .
      #    ports:
      #      - "8080:5173"
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heddle.rule=Host(`heddle.fhub.dev`)"
      - "traefik.http.routers.heddle.entrypoints=https"
      - "traefik.http.routers.heddle.tls=true"
      - "traefik.http.routers.heddle.tls.certresolver=le"
      - "traefik.http.services.heddle.loadbalancer.server.port=5173"
    environment:
      - NODE_ENV=production

  playground:
    build:
      context: ./playground
      dockerfile: Dockerfile
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heddle.rule=Host(`heddle.fhub.dev`) && PathPrefix(`/playground`)"
      - "traefik.http.routers.heddle.entrypoints=https"
      - "traefik.http.routers.heddle.tls=true"
      - "traefik.http.routers.heddle.tls.certresolver=le"
      - "traefik.http.services.heddle.loadbalancer.server.port=80"
    environment:
      - NODE_ENV=production

networks:
  traefik_proxy:
    external: true
