// Code Snippets
export const heroCode = `import "io/http" as http
import "std/transform" as transform
import "std/log" as log

// 1. Define the shape of your data
// Schemas are enforced at compile-time for zero-runtime overhead
schema User = {
    id: int,
    name: string,
    email: string,
    active: bool
}

// 2. Define an atomic step
// Steps are pure functions that operate on immutable Arrow frames
step fetch_users -> User = http.get {
    url: "https://api.example.com/users"
}

// 3. Define the main workflow
workflow process_active_users {
    fetch_users
        | transform.filter { condition: "active == true" }
        | ( // 4. Use first-class PRQL for transformation
            // Zero-copy projections on the underlying Arrow batch
            from input
            select id, name, email
          )
        | log.info { message: "Processed active users" }
}`;

export const imperativeCode = `// 1. Import imperative logic from the Python Host Environment
// These bindings execute via Ray, allowing full access to PyTorch/TensorFlow
import "fhub.dev/deeplearning/models" as ml
import "std/database" as db

// 2. Define steps that wrap this logic
step load_model = ml.load_fraud_model {
    model_path: "/models/v1/fraud.bin"
}

step run_prediction = ml.predict_fraud {
    // 'load_model' is automatically injected as a dependency
    model: load_model
}

// 3. Compose them in a clean, functional pipeline
workflow process_payment {
    // The data source (e.g., http.post) is piped in
    input_payment
        | run_prediction ? handle_model_failure
        | db.write_results
}`;

export const prqlCode = `import "std/database" as db
import "stream/kafka" as kafka
import "std/dashboard" as dash

step users_read = db.query { sql: "SELECT * FROM users" }
step events_read = kafka.read { topic: "user_events" }

workflow user_analytics {
    // 'events_read' output is piped into the PRQL block
    let users_table = users_read

    events_read
        | ( // Join stream against the database table
            from input
            join users_table (user_id == id)
            group {users_table.country} (
                aggregate { event_count = count }
            )
          )
        | dash.update_analytics
}`;

export const errorHandlingCode = `import "std/error" as error
import "std/log" as log

step process_data = external.api_call { ... }

// Define a handler: a dedicated pipeline for errors
handler log_and_swallow = error.handler {
    log.error { message: "API call failed, continuing." }
}

// Define a handler: a dedicated pipeline for errors
handler log_workflow = error.handler {
    log.error { message: "API call failed, continuing." }
}

workflow main_pipeline ? log_workflow {
    // If process_data fails, Heddle executes the 'log_and_swallow' handler
    process_data ? log_and_swallow
}`;

interface FeatureItem {
    title: string;
    description: string;
}

interface LandingContent {
    hero: {
        title: string;
        description: string;
        cta: {
            playground: string;
            specs: string;
        };
    };
    philosophy: {
        title: string;
        description: string;
    };
    prql: {
        title: string;
        description: string;
    };
    errorHandling: {
        title: string;
        description: string;
    };
    engineering: {
        title: string;
        description: string;
        features: FeatureItem[];
    };
    integration: {
        title: string;
        description: string;
        features: FeatureItem[];
    };
    readme: {
        title: string;
        description: string;
    };
}

// Text Content
export const landingContent: LandingContent = {
    hero: {
        title: "Verifiable Logic.\nHost-Core Symbiosis.",
        description: "Heddle bridges the gap between Declarative Orchestration (Workflow) and Imperative Execution (Python Steps) using zero-copy Arrow frames.\nThis separation ensures logic is verifiable, audit-ready, and high-performance.",
        cta: {
            playground: "Play Ground",
            specs: "Read the Specs"
        }
    },
    philosophy: {
        title: "Functional Flow, Imperative Steps",
        description: "Your business logic is imperative: call an API, run a Python model, query a database. Your data flow is functional: filter, transform, join, and aggregate.\n\nHeddle gives you the best of both worlds. You write simple `steps` that wrap your imperative logic, which are then executed by the **Python Host Environment** via Ray. You arrange these steps into clean `workflow` pipelines. The syntax is intentionally simple, making it **easy for humans to audit** and verify—even when that code is **generated by an LLM**."
    },
    prql: {
        title: "First-Class Data Transformation",
        description: "Stop passing opaque SQL strings. Heddle integrates PRQL (Pipelined Relational Query Language) directly into the language, giving you compile-time safety and seamless data flow.\n\nPipe data from any source—a Kafka stream, an HTTP request, or another step—directly into a PRQL block. Join, group, and aggregate data relationally, then pipe the results to the next step."
    },
    errorHandling: {
        title: "Declarative Error Handling",
        description: "Handle failures gracefully with the `?` operator.\n\nDeclaratively attach error-handling `handler` pipelines to any `step` or `workflow`. This ensures your `workflow` can recover or fail gracefully without cluttering your core logic with *try/catch* blocks."
    },
    engineering: {
        title: "Engineered for Resilience & Performance",
        description: "Heddle is a high-performance system leveraging the Ray ecosystem for robust, distributed execution.",
        features: [
            {
                title: "Host-Core Architecture",
                description: "The Heddle Core (Rust/C++) manages state and orchestration, while the Host Environment (Python) executes imperative logic via Ray actors. This symbiosis enables high-performance execution without sacrificing the flexibility of Python ecosystems."
            },
            {
                title: "Zero-Copy Memory Model",
                description: "Powered by Apache Arrow, Heddle eliminates serialization overhead between steps. Data frames are passed by reference, enabling zero-copy reads and writes for maximum throughput in data-intensive applications."
            },
            {
                title: "Time-Travel Debugging",
                description: "Data frames in Heddle are immutable. The runtime preserves execution history, allowing developers to time-travel through the Directed Acyclic Graph (DAG) and inspect the state at any point for precise debugging."
            },
            {
                title: "Efficient Distributed Execution",
                description: "The RayStreamEngine automatically manages micro-batching and backpressure. Workflows are optimized for distributed execution, scaling effortlessly across clusters to handle massive workloads."
            }
        ]
    },
    integration: {
        title: "Integrates With Your Stack",
        description: "Heddle acts as the Agentic Intermediate Layer—the safe execution engine for AI Agents.",
        features: [
            {
                title: "Agentic Intermediate Layer",
                description: "Connect modules like `fhub/postgres`, `fhub/kafka`, `fhub/clickhouse`, and `fhub/llm` to build robust, verifiable systems. Heddle provides the safe, auditable glue between your AI agents and your infrastructure."
            },
            {
                title: "Extensible Connectivity",
                description: "Connect to anything. An expanding standard library provides connectors for databases, messaging, and file formats. The simple *import* system makes it easy to add your own Python-based connectors."
            }
        ]
    },
    readme: {
        title: "Heddle Language Specification",
        description: "A brief overview of the core language constructs."
    }
};
